{% set name = "pytest-metadata" %}
{% set version = "1.5.1" %}
{% set hash_type = "sha256" %}
{% set hash = "26761319ecc916f16dc95f166e41e041d50a6d587d8332300594dfcfda6a7199" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
    - pytest >=2.9.0

  run:
    - python
    - setuptools
    - pytest >=2.9.0

test:
  imports:
    - pytest_metadata
    - pytest_metadata.ci

about:
  home: https://github.com/davehunt/pytest-metadata
  license: MPL 2.0
  license_family: OTHER
  license_file: LICENSE
  summary: 'pytest plugin for test session metadata'

extra:
  recipe-maintainers:
    - birdsarah
    - davehunt
