{% set name = "pytest-metadata" %}
{% set version = "1.10.0" %}
{% set hash_type = "sha256" %}
{% set hash = "b7e6e0a45adacb17a03a97bf7a2ef60cc1f4e172bcce9732ce5e814191932315" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - setuptools_scm
    - pytest >=2.9.0

  run:
    - python
    - setuptools
    - pytest >=2.9.0

test:
  imports:
    - pytest_metadata
    - pytest_metadata.ci

about:
  home: https://github.com/davehunt/pytest-metadata
  license: MPL 2.0
  license_family: OTHER
  license_file: LICENSE
  summary: 'pytest plugin for test session metadata'

extra:
  recipe-maintainers:
    - birdsarah
    - davehunt
    - nicoddemus
