travis:
  secure:
    BINSTAR_TOKEN: cFX2yVLoWsZflmd03M/YvjjPT8vHuZMomzN5HnJ83sJgUVab541zk2RKmE3zYvGntqL7gpKmGJv34dApkaBVjZKtZREloQHSP/WBGdg6A0JmuX9irqrG3mAw8lhaeSeG6/l4DgjNSExfx2ZER/ft8yFCZ+YATqhaq4quJv+U7qqoPWP2pKpiKPp8EYleYUSkNr9p150izTtN30Bk0Y8UWfjdl0a3oB7mClAm7WS8F5lMpa5AWdjFQDxpYKRWa4i++1UohOTeUT0Q5fQ/NwdeTlzEdFEu2EYlEPQftL/ySboNs60di3hvfVWRzQfKgAe6HAfGZj6ylMi8c9qLncZBx057Km5EpFcc3cVjzRdFLc5Z0vngdsdD7dAYlx/8JDKuOZf05A2TAlKYVFNbfOLXBwa0jjdARl5X6QYC9/YXxCbZPvsMM1qzqK3k330/7rkTdabRiCvQNyIkk0bnWgTjPgpWKHA+2jV450fMKXt6bF9VD5apdJ6HRWm9OweNIdTSrJuYLNY0p7W2VmMjF/03or+RPW20H58mIvMJ4ZH/q++94Qp0iAjes66C6XkEoh2HDV20mEyvLdct7tE4Ar9EJf588l/3xz5TXJNr1DB3OLkp25yqXS/I+CW3hGxDS0bdoQ7ZT/Pfkml2x9IigsGRF0JuU/NyhPorOwtnwRfg4Qc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
