travis:
  secure:
    BINSTAR_TOKEN: gDdH/Ooc2Cd3GR9HHyR9a1UP8xcNm1FjCWKNXDp4/bMEotjsUgbXi4a71jJAkH3/8WgPWQXbzdXWMA1yjB+sHnLBcn9dD0QOcdCiyTTegfdch33zYX3XLfkwTaLdpjjXTUhfR2SXxY/ZjPsCXXKOMQVSH9EU2gKL/iGADy3FUOcVAVGbnAYiLOUGY5PMBwRGLQpYXUhH69AgRcCPaEBuR+Pd0m9eK5VY4VyB42yf1bV3GykIahrqp0c084QsLqvxb8UzTWFXv1gkA2OGhPARk7o9PBVyOHRunoWUeAVTZ3VEJAscecQZQpHxIz/myQ7DrqQI0uZpFjlLn/NVUdGFaTZrqLAkreoe6t1jCzB+ZsqNvkodYECyAPr57YB25zj1UKx3YaZpqQmgvaFuMzdLZooiZlWZnGjzriEdPfmCa96nAdogz/Y8XnK6KM5ncSJ4xfTHS9D0hcOi+XDfRBWbNL0jlFrzeEsGYBkJXC9xvOxwgpbV+t3q4+gNhYb1TkhaojeX06hELkk/xZt/wDBxaqp+xlJo8PbqjvtL07c6RCQn0c7bqEhh0stkdZKO1W0tutTiqdc1Lv3L72YVHOKdRtdCqxzdQJEpginTc4tSLIvKmm5qZw8n2ME6dY72p8+sc3DGt1ucHoPljwhUjTdvpomlzD8X/NFYZXGZbABvzbQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
